---
application:
  name: "Automation Exercise"
  url: "https://automationexercise.com/"

users:
  - name: "admin"
    username: "admin"
    password: "admin1"

  - name: "tester"
    username: "tester"
    password: "tester1"

  - name: "user"
    username: "user"
    password: "user1"


tests:
  browser: CHROME # FIREFOX, EDGE, SAFARI
  features: "src/main/resources/features/01Login.feature"
  tags: ""
  dryRun: false



chrome:
  version: 116
  options:
    - "--start-maximized"
   # - "--incognito" # gizli moddan acar

edge:
  version: 110
  options:
    - "--start-maximized"


firefox:
  version: 62
  options:
    - ""
    - ""

variables:
  var1: "variable1"
  var2: "variable2"
  var3: "variable3"
  var4: "variable4"
  aaa: "bbbbbb"
  ali.veli.deli: "121312312312"